### ISSUE TITLE
assets 404 and invalid content-type

### ISSUE THREAD

**Issue by chrisjbrown** [KiritchoukC/nuxt-on-firebase-example#4]
I'm having issues running locally with the commands

```
build:firebase
start:firebase
```

I'm getting either 404 or content-type invalid for my .js and .css files

I can see that the public directory has my built files at 
`/public`, `/public/client`, `/public/server`

I've tried cloning your repo as well and I have the same problem

![Screenshot 2020-03-30 at 12 14 49](https://user-images.githubusercontent.com/1250638/77901784-760a7a80-7280-11ea-9f74-a731c21a4143.png)

**Comment by IHIutch** [comment]
Same issue here, tried modifying `build.publicPath:'/_nuxt/'` but no luck there either
