### ISSUE TITLE
Timeout when yarn start:firebase

### ISSUE THREAD

**Issue by jonalxh** [KiritchoukC/nuxt-on-firebase-example#8]
Hi, I was following your post but I had troubles, so I decided to clone your repo and it throws me the same error on browser when y run` yarn start:firebase` :

`Timed out waiting for function to respond.`

I've installed all dependencies and ran yarn build:firebase, it finishes right but the problem is when I try to run it with firebase, I've logged into my account and chosen my project.

Do you know how to solve it?

**Comment by KiritchoukC** [comment]
Hi @jonalxh ,

Can you please paste the console output of `yarn build:firebase` and `yarn start:firebase` ?

**Comment by jonalxh** [comment]
Hi @KiritchoukC ,
I've solved it by updating firebase modules on functions folder:

- "firebase-admin": "^8.10.0",
-  "firebase-functions": "^3.6.1"
